"""initial schema

Revision ID: 53668922f4f7
Revises: a083ff38da6e
Create Date: 2026-06-14 02:27:20.373173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53668922f4f7'
down_revision: Union[str, Sequence[str], None] = 'a083ff38da6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('designation', sa.String(), nullable=True))
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_column('employees', 'manager_id')
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.drop_column('employees', 'designation')
    # ### end Alembic commands ###
